services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    platform: linux/x86_64
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    platform: linux/x86_64
    restart: always
    ports:
      - 9866:9866
      - 9864:9864
    depends_on:
      - namenode
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop

  resourcemanager:
    image: coomia/hadoop3.2-resourcemanager:1.0
    container_name: resourcemanager
    platform: linux/x86_64
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 datanode:9866"
    env_file:
      - ./hadoop.env
    volumes:
      - /Users/manuelmontero/MM_DLK:/MM_DLK
    networks:
      - hadoop

  nodemanager:
    image: coomia/hadoop3.2-nodemanager:1.0
    container_name: nodemanager
    platform: linux/x86_64
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 datanode:9866"
    env_file:
      - ./hadoop.env
    volumes:
      - /Users/manuelmontero/MM_DLK:/MM_DLK
    networks:
      - hadoop

  historyserver:
    image: coomia/hadoop3.2-historyserver:1.0
    container_name: historyserver
    platform: linux/x86_64
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 datanode:9866"
    env_file:
      - ./hadoop.env
    volumes:
      - /Users/manuelmontero/MM_DLK:/MM_DLK
    networks:
      - hadoop

  hive-server:
    hostname: hive-server
    container_name: hive-server
    image: bde2020/hive:2.3.2-postgresql-metastore
    platform: linux/x86_64
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    networks:
      - hadoop
  hive-metastore:
    hostname: hive-metastore
    container_name: hive-metastore
    platform: linux/x86_64
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 datanode:9866 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    networks:
      - hadoop
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    platform: linux/x86_64
    networks:
      - hadoop

  zookeeper:
    image: coomia/zookeeper:0.1
    container_name: zookeeper
    platform: linux/x86_64
    ports:
      - 2181:2181
    networks:
      - hadoop

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "arkuser:1:1, arkevent:1:1"
      KAFKA_TRANSACTION_MAX_TIMEOUT_MS: "7200000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hadoop

#  kafkamanager:
#      image: fjardim/kafkamanager
#      container_name: kafkamanager
#      platform: linux/x86_64
#      hostname: kafkamanager
#      environment:
#        ZK_HOSTS: zookeeper:2181
#      ports:
#        - 9000:9001
#      depends_on:
#        - kafka
#      deploy:
#        resources:
#          limits:
#            memory: 200m

  jobmanager:
    image: coomia/flink:1.14
    container_name: jobmanager
    platform: linux/x86_64
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - hadoop

  taskmanager:
    image: coomia/flink:1.14
    container_name: taskmanager
    platform: linux/x86_64
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - hadoop

networks:
  default:
    name: net
  hadoop:
    driver: bridge
